language: objective-c
os: osx
osx_image: xcode9.3beta
script:
- sudo gem install xcpretty
- xcodebuild -project Nexum.xcodeproj -scheme Nexum -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0' test-without-building | xcpretty