remote_theme: vsanthanam/jekyll-docs-theme
# show_downloads: true
name: Nexum

project:
  version: 1.0
  download_url: https://www.github.com/vsanthanam/Nexum/releases

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

    docs: CC BY 3.0
    docs_url: http://creativecommons.org/licenses/by/3.0/

links:
    header:
      - title: GitHub
        url: https://www.github.com/vsanthanam/Nexum
      - title: Documentation
        url: https://code.vsanthanam.com/Nexum/Documentation/index.html
    footer:
      - title: GitHub
        url: https://www.github.com/vsanthanam/Nexum
      - title: Issues
        url: https://www.github.com/vsanthanam/Nexum/issues?state=open

ui:
    header:
        color1: "#0250c5"
        color2: "#d43f8d"
        trianglify: true

social:
    github:
        user: vsanthanam
        repo: Nexum
    twitter:
        enabled: false
        via:
        hash:
        account: 
    facebook:
        enabled: false
        profileUrl:

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock